# Generated by Django 4.2.1 on 2024-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('package_type', models.CharField(max_length=20)),
                ('hostel', models.CharField(max_length=300)),
                ('insurance', models.CharField(max_length=20)),
                ('riding_gears', models.CharField(max_length=20)),
                ('trainer_experience', models.CharField(max_length=100)),
                ('hours_num', models.CharField(max_length=200)),
            ],
        ),
    ]
