# Generated by Django 4.2.1 on 2024-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
