# Generated by Django 4.2.1 on 2024-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0002_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
