# Generated by Django 4.2.1 on 2024-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0003_alter_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
