# Generated by Django 4.2.1 on 2024-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0004_alter_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('Package_id', models.IntegerField()),
                ('advance_amount', models.BigIntegerField()),
            ],
        ),
    ]
