# Generated by Django 4.2.1 on 2024-02-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('package_type', models.CharField(max_length=30)),
                ('trainer', models.CharField(max_length=20)),
            ],
        ),
    ]
