# Generated by Django 4.2.1 on 2024-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('trainer', 'trainer')], default='user', max_length=10),
        ),
    ]
